import { Provider } from 'react-redux';
import { createStore } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import { allReducers } from "../store/reducers/allReducers"
import "../styles/styles.scss"
import "../styles/spinner.css"
import type { AppProps } from 'next/app'
import Navigation from "../components/Navigation"
import Head from "next/head"
import Footer from "../components/Footer"

const myStore = createStore(allReducers, composeWithDevTools());

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={myStore}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <Component {...pageProps} />

      <Footer />
    </Provider>
  )
}
